#spring: 
#  datasoruce: druid
  
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: databank-dbserver
  redis:
    host: 172.16.7.119
    port: 26379
  data:
    mongodb:
      uri: mongodb://172.16.7.140:27017/datastation
  datasource:
    #权限数据源
    databank-authorization:
      name: databank_authorization
      jdbc-url: jdbc:mysql://172.16.7.119:23306/databank_authorization?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: huitone2214
      #使用本地库
      #jdbc-url: jdbc:mysql://localhost:3306/databank_authorization?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      #username: root
      #password: 123456
      
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 40
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    #api平台数据源
    api-platform:
      name: api_platform
      jdbc-url: jdbc:mysql://172.16.7.119:23306/api_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: huitone2214
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  #mapper-locations: classpath:mapping/*.xml #这里是mapper的配置文件
  #type-aliases-package: com.htgx.databank.dbserver.entity #这里是实体类的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://databank.eureka:28761/eureka/
#      defaultZone: http://localhost:8002/eureka/
#      defaultZone: http://172.16.7.119:28761/eureka/ #指定服务注册中心
server:
  port: 8762
  servlet: 
    context-path: /databank-dbserver
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enable: true
    
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
#系统管理默认菜单id
system: 
  management: 
    menuId: 14
    
#davinci创建用户接口访问地址  开发地址为服务器地址
davinci-api-url: http://172.16.7.119:8181/dev/api/v3/login/createUser
#zuul 配置详情
#zuul:
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 10000
#  routes:
#    DATABANK-DEMO:
#      serviceId: DATABANK-DBSERVER
#      path: /demo/**
#      stripPrefix: false
datastation:
  license:
    licenseKey: datastation:license
    timeout: 86400