server:
  port: 8086
 
spring:
    application:
       name: api-service
    datasource:
        name: test
        url: jdbc:mysql://databank.mysql:3306/api_platform?useSSL=false&characterEncoding=utf8
        username: databank
        password: HTq1a2z3%4
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
eureka:
  client:
    service-url:
      defaultZone: http://databank.eureka:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#springboot   mybatis
#jiazai mybatis peizhiwenjian
mybatis:
   mapper-locations : classpath:mapper/*Mapper.xml
#mybatis.config-location= classpath:SqlMapConfig.xml
   type-aliases-package : com.api.entity
logging: 
    file: logback.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count==countSql
  returnPageInfo: check