server:
  port: 9011
  servlet:
    multipart:
      max-file-size: 2M
    context-path: /databank-kg
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enable: true
eureka:
  instance:
    #断开时间
    lease-expiration-duration-in-seconds: 30
    #心跳时间
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
#      defaultZone: http://172.16.7.119:28761/eureka/
spring:
#  application:
#    name: databank-kg
  redis:
    host: 172.16.7.119
    port: 26379
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    name: databank_authorization
    jdbc-url: jdbc:mysql://172.16.7.119:23306/databank_kg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: root
    password: huitone2214
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  data:
 #neo4j配置 	
    neo4j:
      username: neo4j
      password: htgx123456
      uri: bolt://172.16.8.2:7687
#      uri: bolt://172.16.7.142:7687/
 ###es配置
    es:
      host: 172.16.8.4
      port: 9200

mybatis:
  mapper-locations: classpath:mapper/*.xml #这里是mapper的配置文件
  type-aliases-package: com.htgx.databank.dataMeta.entity #这里是实体类的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

kbqa:
  url: http://172.16.8.5:8888/getCypher