server:
  port: 9009
  servlet:
    multipart:
      max-file-size: 2M
    context-path: /databank-filemanagement
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eureka:
    enable: true
eureka:
  instance:
    #断开时间
    lease-expiration-duration-in-seconds: 30
    #心跳时间
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
spring:
#  application:
#    name: databank-filemanagement
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    name: databank_metadata
    url: jdbc:mysql://172.16.7.119:23306/databank_metadata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowMultiQueries=true
    username: root
    password: huitone2214
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml #这里是mapper的配置文件
  type-aliases-package: com.htgx.databank.fileManagement.entity #这里是实体类的包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# fastdfs:
#   #配置文件路径 FASTDFS不支持JAR包内路径 ./ 表示JAR包所在目录
#   clientConfPath: ./config/fastdfs-client.properties
#   #应用组分配
#   group: dev1
#   #是否过期  0 不过期  1 过期
#   defauleIsDueTime: 1
#   #有效时间 时间设计为过期时生效 7天  7*24*60*60 单位秒
#   defauleDueTime: 604800
fdfs:
  #应用组分配
  group: dev1
  #是否过期  0 不过期  1 过期
  defauleIsDueTime: 1
  #有效时间 时间设计为过期时生效 7天  7*24*60*60 单位秒
  defauleDueTime: 604800
  # 链接超时
  connect-timeout: 60
  # 读取时间
  so-timeout: 60
  # 生成缩略图参数
  thumb-image:
    width: 150
    height: 150
  tracker-list: 
    - 172.16.7.119:8300
  pool:
    max-total: -1